<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
		<section>
			<h2>L'en-tête de niveau&#160;2 (h2)</h2>

			<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
			<section>
				<h3>L'en-tête de niveau&#160;3 (h3)</h3>

				<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
				<section>
					<h4>L'en-tête de niveau&#160;4 (h4)</h4>

					<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
					<section>
						<h5>L'en-tête de niveau&#160;5 (h5)</h5>

						<div class="cn-toppage"><a href="#cn-tphp" title="Retourner au haut de la page">Haut de la page</a></div>
						<section>
							<h6>L'en-tête de niveau&#160;6 (h6)</h6>

							<p>CONTENU (un mélange de texte et d'images ou de graphiques est prévu)</p>
						</section>
					</section>
				</section>
			</section>
		</section>
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
