<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<div id="cn-sig"><img src="theme-clf2-nsi2/images/sig-eng.gif" width="372" height="20" alt="Government of Canada" title="Government of Canada" /></div>
		<div id="cn-wmms"><img src="theme-clf2-nsi2/images/wmms.gif" width="83" height="20" alt="Symbol of the Government of Canada" title="Symbol of the Government of Canada" /></div>

		<!-- Banner begins / Début de la bannière -->
		<div id="cn-leaf"></div>
		<div id="cn-banner" role="banner">
			<p id="cn-banner-text">Name of Institution</p>
			<p>[www.]mainsite-siteprimaire.gc.ca</p>
		</div>
		<!-- Banner ends / Fin de la bannière -->

		<nav role="navigation">
			<!-- Common menu bar begins / Début de la barre de menu commune -->
			<div id="cn-cmb">
				<h2>Common menu bar</h2>
				<ul>
					<li id="cn-cmb1"><a href="theme-clf2-nsi2/3col-theme-clf2-nsi2-fra.html" lang="fr" title="Français - Version française de cette page">Français</a></li>
					<li id="cn-cmb2"><a href="#" title="Home - Main page of the Web site">Home</a></li>
					<li id="cn-cmb3"><a href="#" title="Contact Us - Important contact information">Contact Us</a></li>
					<li id="cn-cmb4"><a href="#" title="Help - Information about using the Web site">Help</a></li>
					<li id="cn-cmb5"><a rel="search" href="#" title="Search - Search the Web site">Search</a></li>
					<li id="cn-cmb6"><a rel="external" href="http://www.canada.gc.ca/home.html" title="canada.gc.ca - Government of Canada Web site">canada.gc.ca</a></li>
				</ul>
			</div>
			<!-- Common menu bar ends / Fin de la barre de menu commune -->

			<!-- Breadcrumb begins / Début du fil d'Ariane -->
			<div id="cn-bcrumb">
				<h2>Breadcrumb</h2>
				<ol>
					<li><a href="#" title="Home - Main page of the Web site">Home</a>&#160;&#62;</li>
					<li><a href="#">Level&#160;1</a>&#160;&#62;</li>
					<li><a href="#">Level&#160;2</a>&#160;&#62;</li>
					<li><abbr title="Common Look and Feel">CLF</abbr> 2.0 Theme - HTML5 - Web Experience Toolkit (WET)</li>
				</ol>
			</div>
			<!-- Breadcrumb ends / Fin du fil d'Ariane -->
		</nav>
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
