<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<div id="cn-sig"><img src="theme-clf2-nsi2/images/sig-fra.gif" width="372" height="20" alt="Gouvernement du Canada" title="Gouvernement du Canada" /></div>
		<div id="cn-wmms"><img src="theme-clf2-nsi2/images/wmms.gif" width="83" height="20" alt="Symbole du gouvernement du Canada" title="Symbole du gouvernement du Canada" /></div>

		<!-- Banner begins / Début de la bannière -->
		<div id="cn-leaf"></div>
		<div id="cn-banner" role="banner">
			<p id="cn-banner-text">Nom de l'institution</p>
			<p>[www.]siteprimaire-mainsite.gc.ca</p>
		</div>
		<!-- Banner ends / Fin de la bannière -->

		<nav role="navigation">
			<!-- Common menu bar begins / Début de la barre de menu commune -->
			<div id="cn-cmb">
				<h2>Barre de menu commune</h2>
				<ul>
					<li id="cn-cmb1"><a href="theme-clf2-nsi2/3col-theme-clf2-nsi2-eng.html" lang="en" title="English - English version of the Web page">English</a></li>
					<li id="cn-cmb2"><a href="#" title="Accueil - Page principale du site Web">Accueil</a></li>
					<li id="cn-cmb3"><a href="#" title="Contactez-nous - Coordonnées importantes">Contactez-nous</a></li>
					<li id="cn-cmb4"><a href="#" title="Aide - Renseignements sur la façon d'utiliser le site Web">Aide</a></li>
					<li id="cn-cmb5"><a rel="search" href="#" title="Recherche - Recherche dans le site Web">Recherche</a></li>
					<li id="cn-cmb6"><a rel="external" href="http://www.canada.gc.ca/accueil.html" title="canada.gc.ca - Site Web du gouvernement du Canada">canada.gc.ca</a></li>
				</ul>
			</div>
			<!-- Common menu bar ends / Fin de la barre de menu commune -->

			<!-- Breadcrumb begins / Début du fil d'Ariane -->
			<div id="cn-bcrumb">
				<h2>Fil d'Ariane</h2>
				<ol>
					<li><a href="#" title="Accueil - Page principale du site Web">Accueil</a>&#160;&#62;</li>
					<li><a href="#">Niveau&#160;1</a>&#160;&#62;</li>
					<li><a href="#">Niveau&#160;2</a>&#160;&#62;</li>
					<li>Thème <abbr title="Normalisation des sites Internet">NSI</abbr> 2.0 - HTML5 - Boîte à outils de l'expérience Web (BOEW)</li>
				</ol>
			</div>
			<!-- Breadcrumb ends / Fin du fil d'Ariane -->
		</nav>
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
