<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
			<section role="search">
				<h3><label for="cn-search">Recherche</label></h3>
				<form action="#" method="post">
				<div id="cn-search-box">
					<input id="cn-search" name="cn-search" type="search" size="18" maxlength="40" /><input id="cn-search-submit" name="cn-search-submit" type="submit" value="Recherche" />
					<a rel="search" href="#">Recherche avancée</a>
				</div>
				</form>
			</section>
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
