<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<div id="cn-sig"><img src="theme-clf2-nsi2/images/sig-eng.gif" width="372" height="20" alt="Government of Canada / Gouvernement du Canada" title="Government of Canada / Gouvernement du Canada" /></div>
		<div id="cn-wmms"><img src="theme-clf2-nsi2/images/wmms.gif" width="83" height="20" alt="Symbol of the Government of Canada / Symbole du gouvernement du Canada" title="Symbol of the Government of Canada / Symbole du gouvernement du Canada" /></div>
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
