<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<!-- English message begins / Début du message en anglais -->
		<div id="cn-left-msg">
		<section>
			<h2>Message title (h2)</h2>
			<p>Message message message message message message message message message message message message message message message message message message message message.</p>
		</section>
		</div>
		<!-- English message ends / Fin du message en anglais -->

		<!-- French message begins / Début du message en français -->
		<div id="cn-right-msg" lang="fr">
		<section>
			<h2>Titre du message (h2)</h2>
			<p>Message message message message message message message message message message message message message message message message message message message message.</p>
		</section>
		</div>
		<!-- French message ends / Fin du message en français -->
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
