<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<div id="cn-sig"><img src="theme-clf2-nsi2/images/sig-fra.gif" width="372" height="20" alt="Gouvernement du Canada / Government of Canada" title="Gouvernement du Canada / Government of Canada" /></div>
		<div id="cn-wmms"><img src="theme-clf2-nsi2/images/wmms.gif" width="83" height="20" alt="Symbole du gouvernement du Canada / Symbol of the Government of Canada" title="Symbole du gouvernement du Canada / Symbol of the Government of Canada" /></div>
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
