<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<div id="cn-in-pd">
			<ul>
				<li id="cn-inotices-link-left">
					<dl class="cn-doc-dates" role="contentinfo">
						<dt>Date Modified:</dt>
						<dd><span><time>2010-08-09</time></span></dd>
					</dl>
					<a href="#" rel="license">Important Notices</a><br />
				</li>
				<li id="cn-inotices-link-right" lang="fr">
					<dl class="cn-doc-dates" role="contentinfo">
						<dt>Date de modification&#160;:</dt>
						<dd><span><time>2010-08-09</time></span></dd>
					</dl>
					<a href="#" rel="license">Avis importants</a>
				</li>
			</ul>
		</div>
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
