<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<!-- Message space begins / Début de l'espace de message -->
		<div id="cn-msg-space" role="banner">
			<div id="cn-upper-msg"></div>
			<div id="cn-lower-msg">
				<p id="cn-left-msg">Name of Institution</p>
				<p id="cn-right-msg" lang="fr">Nom de l'institution</p>
			</div>
		</div>
		<!-- Message space ends / Fin de l'espace de message -->

		<div role="navigation">
		<nav>
			<h2>Language selection / <span lang="fr">Sélection de la langue</span></h2>
			<ul id="cn-ef-lang-links">
				<li><a href="theme-clf2-nsi2/3col-theme-clf2-nsi2-eng.html" title="English - English version of the Web site">English</a></li>
				<li lang="fr"><a href="theme-clf2-nsi2/3col-theme-clf2-nsi2-fra.html" title="Français - Version française de ce site Web">Français</a></li>
			</ul>
		<div id="cn-wmms"><img src="images/wmms.gif" width="83" height="20" alt="Symbol of the Government of Canada / Symbole du gouvernement du Canada" title="Symbol of the Government of Canada / Symbole du gouvernement du Canada" /></div>
		</nav>
		</div>
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
